# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2a4c5f2bbfa48f47bde2c812b0f12a0596039af356dd24746b35565031615e97f49836e7f6f279ff308542408fd4bc16b9414596dca2996489dc71a14e81c805

test:
  secret_key_base: 8a58e244d0325b7cef73113e0f99c81fa9d9ca08e2e4e7489a5dd09c2f14ef52cd988b56071568321d0e7943523c665bdd09c7a5e0acf5f395e5534595ad926c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
